[[desync]]
arch = "aarch64"
git-tree-sha1 = "86d01228b808be70f6fd413755f2191ab22f6b6b"
os = "macos"

    [[desync.download]]
    sha256 = "18f3f1a02e195fcc50a4e133d741d22c82f83a3e7a7d6df499bc7abb382663d0"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.aarch64-apple-darwin.tar.gz"
[[desync]]
arch = "aarch64"
git-tree-sha1 = "0a02e86997898b0daaf46761ad262b8f7c74d838"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "d70745a7380a05b9c5e7a34bef6b97f0e3d00eb7aea356e0818386a3b8c758a9"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.aarch64-linux-gnu.tar.gz"
[[desync]]
arch = "aarch64"
git-tree-sha1 = "0a02e86997898b0daaf46761ad262b8f7c74d838"
libc = "musl"
os = "linux"

    [[desync.download]]
    sha256 = "d70745a7380a05b9c5e7a34bef6b97f0e3d00eb7aea356e0818386a3b8c758a9"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.aarch64-linux-musl.tar.gz"
[[desync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "525325ade24c6c73d3eb3db19d88b64ca7963ab2"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "09bc7921131f1dc2eeacd3d3258bbac3d619f818750347957cba30f38967bb3c"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.armv6l-linux-gnueabihf.tar.gz"
[[desync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "525325ade24c6c73d3eb3db19d88b64ca7963ab2"
libc = "musl"
os = "linux"

    [[desync.download]]
    sha256 = "09bc7921131f1dc2eeacd3d3258bbac3d619f818750347957cba30f38967bb3c"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.armv6l-linux-musleabihf.tar.gz"
[[desync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1777339ced356b5cad7e1ad862fc8bea886240e2"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "45f7c7aa4ee04f43e6639285cd8eed6e3e1862c550167bde49347dc87a5bcc6d"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.armv7l-linux-gnueabihf.tar.gz"
[[desync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1777339ced356b5cad7e1ad862fc8bea886240e2"
libc = "musl"
os = "linux"

    [[desync.download]]
    sha256 = "45f7c7aa4ee04f43e6639285cd8eed6e3e1862c550167bde49347dc87a5bcc6d"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.armv7l-linux-musleabihf.tar.gz"
[[desync]]
arch = "i686"
git-tree-sha1 = "818c15a2879f8784ad2bef99919e75237e9d9c5d"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "bc8a265f9ebfe2f744defc3508de4ee9e37643ca64535c35d8e5583815f7a9c4"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.i686-linux-gnu.tar.gz"
[[desync]]
arch = "i686"
git-tree-sha1 = "818c15a2879f8784ad2bef99919e75237e9d9c5d"
libc = "musl"
os = "linux"

    [[desync.download]]
    sha256 = "bc8a265f9ebfe2f744defc3508de4ee9e37643ca64535c35d8e5583815f7a9c4"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.i686-linux-musl.tar.gz"
[[desync]]
arch = "i686"
git-tree-sha1 = "d5e7fe0db96288501efdacf490f504024ae67124"
os = "windows"

    [[desync.download]]
    sha256 = "166c18bf1df534f1017fcb3ee246595f2fa0db507744256e880f391b4b1d91d7"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.i686-w64-mingw32.tar.gz"
[[desync]]
arch = "powerpc64le"
git-tree-sha1 = "c81961c5333e546d96c919700458bc8ee494b820"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "46e405bb2889eecf33ab9c2517140bb2ccefafa78f0ca0649d2814dfd9e4decd"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.powerpc64le-linux-gnu.tar.gz"
[[desync]]
arch = "riscv64"
git-tree-sha1 = "4b4b6fd215f771aa7163c76ce311ad52a90c446f"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "412913e29396e671cf8a3d75f41dd4674e18c91bd269082e9f43f922258f0dba"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.riscv64-linux-gnu.tar.gz"
[[desync]]
arch = "x86_64"
git-tree-sha1 = "082654d1f4320551fd194809cafc6133ed9c9996"
os = "macos"

    [[desync.download]]
    sha256 = "5ab915a31a3bc1ab95bd31edee5c1d22aeb711ec8799277635efeb4e90045a2e"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.x86_64-apple-darwin.tar.gz"
[[desync]]
arch = "x86_64"
git-tree-sha1 = "9a4f635aa6217d3c29383c757b01c571ab0c6a8c"
libc = "glibc"
os = "linux"

    [[desync.download]]
    sha256 = "910f78c9149b776e426e90890181eff962b6b2d19b40a6c0469a4faa390c31fe"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.x86_64-linux-gnu.tar.gz"
[[desync]]
arch = "x86_64"
git-tree-sha1 = "7cabd50ad7f994fa155ed12640c81076da469e8f"
libc = "musl"
os = "linux"

    [[desync.download]]
    sha256 = "7d1fb3d4a96349b899e507866cc2b36efa67eee1cb8c7ae6e658cfdcdaafb081"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.x86_64-linux-musl.tar.gz"
[[desync]]
arch = "x86_64"
git-tree-sha1 = "fb63c9f623a3f7034c184fa40a00f7b11b267d40"
os = "windows"

    [[desync.download]]
    sha256 = "99132afd805a47e908c62cf42b1d36affa2e930e5fe6ca86f8908f6416e86e3a"
    url = "https://github.com/JuliaBinaryWrappers/desync_jll.jl/releases/download/desync-v0.9.6+0/desync.v0.9.6.x86_64-w64-mingw32.tar.gz"
